# Generated by Django 3.0 on 2019-12-19 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberfee',
            name='paydate',
            field=models.DateField(),
        ),
    ]
