# Generated by Django 3.0 on 2019-12-24 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0004_auto_20191224_2301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='photo',
            field=models.ImageField(default='default.jpg', upload_to=''),
        ),
    ]
